### ISSUE TITLE
PHP Fatal error

### ISSUE THREAD

**Issue by bivilbi** [leon-mbs/zstore#104]
Добрый день.
Ставил и с гита, и с пункта 2.
При попытке захода получаю 500.
В логах следующее.
PHP Fatal error:  Access level to App\\Entity\\Doc\\Document::__construct() must be public (as in class ZCL\\DB\\Entity) in /****/public_html/app/entity/doc/document.php on line 0

В чем может быть проблема?
Спасибо.
Debian 9
php 7.4.9
10.1.45-MariaDB
Vestacp

**Comment by leon-mbs** [comment]
это  какая  то  фигня  в  новых  версиях  PHP считает  что там ошибка
в  файле   \app\entity\doc\document.php
замените
protected function __construct($row = null)
на
public function __construct($row = null)

вт, 11 авг. 2020 г. в 08:57, bivilbi <notifications@github.com>:

**Comment by bivilbi** [comment]
Да.
Изменил и все нормально стало.
Спасибо.
