### ISSUE TITLE
Словил ошибку 

### ISSUE THREAD

**Issue by yuri25** [leon-mbs/zstore#157]
Добрый день, спасибо за систему. Подскажите пожалуйста - ввел в Мои задачи поиск текст, причем и бессмысленный и содержащий слово из созданной задачи - выдает такое.
Component 'App\Pages\Jobs' with ID '' is not direct for owner ID 'nlist'
91
/*/*/*/*/*/*/site.ru/vendor/leon-mbs/zippy/core/html/htmlcontainer.php

**Comment by leon-mbs** [comment]
исправлено
