### ISSUE TITLE
Не ошибка но неудобно...

### ISSUE THREAD

**Issue by yuri25** [leon-mbs/zstore#172]
Ребята, может вы доработаете систему, чтобы в системе где то отражалась информация о текущей версии системы и какие нибудь уведомления, типа обновитесь до версии 5.2.1 Скачайте архив и выполните update510to520.sql. 
Может оно конечно и не нужно, но думаю было бы более четко все.
Вот я сейчас выполнил в консоли: git pull, затем composer --no-dev update, затем скачал архив с гита и выполнил импорт через PMA вот этот файлик update510to520.sql.
Вот казалось бы все обновил.... Однако при входе на сайт вместе с логином, паролем и каптчей висит сообщение Доступна новая версия v5.2.1 Открыть... 
А может это где то и есть внутри системы, просто я не нашел?

**Comment by leon-mbs** [comment]
не  совсем  понятна  проблема
текущая версия  внизу  на  странице  логина
если  есть новая  пишется   под  логином 
 по  ссылке  переходите  и читаете  как  обновлять

И  зачем  выкачали  архив  если  уже  сделали  pull  c гитхаба?

**Comment by yuri25** [comment]
Я скачал, чтобы разархивировать и выполнить импорт файла через PMA - update510to520.sql. 
Я проделал то, что написал выше, но на странице логина по прежнему висит надпись, что у меня версия 5.1.0
![image](https://user-images.githubusercontent.com/253228/124435581-ccb50d00-dd7d-11eb-8437-a1c87ccd7841.png)

Значит я что то не сделал или неправильно сделал....

**Comment by yuri25** [comment]
Сейчас поставлю с нуля, сайт все равно тестовый.

**Comment by leon-mbs** [comment]
текущая  версия хранится  в  этом файле
https://github.com/leon-mbs/zstore/blob/master/www/app/pages/userlogin.php
новая  запрашивается  с  офсайта
там  есть ссылка  на  version,json

потом сравнивается
