### ISSUE TITLE
Бронь

### ISSUE THREAD

**Issue by Vladzimir** [leon-mbs/zstore#173]
Я так понимаю, что механизма бронирования товара в системе не реализовано?

**Comment by leon-mbs** [comment]
почему же.  Делаете  накладную  передним  числом  проводите по  складу вот  вам и бронирование

**Comment by Vladzimir** [comment]
А как тогда посмотреть бронь-остаток? И как удалять такую бронь, если что?

**Comment by leon-mbs** [comment]
посмотреть  модно  по  движению  по складу  будущими  датами.  можно  и специальный  отчет  сделать  если будет  востребовано.
чтобы  вернуььь товар  нужно  просто отменить  докумнт и все   проводки  по  складу  откатятся

**Comment by Vladzimir** [comment]
Хотелось бы просто видеть склад-заказано, даже без самого механизма бронирования.

**Comment by leon-mbs** [comment]
в  данном  случае  возникает  вопрос  что  считать заказаным.  по  каким  документам  это  определять

**Comment by Vladzimir** [comment]
Логично же - по заказу.

**Comment by leon-mbs** [comment]
заявка поставщику еще  не  означает  что  товар  там  есть  
опять  же  кто работает  по предоплате  надо  оплатить  счет
пока  не  оплачен  тоже  нельзя  считать  что  заказано.
кроме  этого надо  потом  как  то  отмечать  что  заказ  выполнен

Все это  конешно  реализуемо  но  идеология  прокта - максимальная  простоа  в  использовании и в  разработке.
нужны  серезные  основания  чтобы  усложнять логику  и код

особенно  когда  ресь идет  о  стандартной версии  где  большинство  этим  ользоватся  не  будет

**Comment by Vladzimir** [comment]
Имелось ввиду именно по заказу от покупателя, а не поставщику.
Ситуация простая. ИМ, заказы комплектуются от 3 до 5 дней, товар продается по наличию.
И для полной картины необходимо видеть сколько товаров на складе, сколько заказано.

**Comment by leon-mbs** [comment]
ну  отчет  по незакрытым  заказам  пожалуй  имеет  смысл
добавлю в  следующем релизе
