### ISSUE TITLE
Немае можливості виводу категорій у вигляди дерева. Не можливо встановити порядок категорій.  

### ISSUE THREAD

**Issue by AlexFromKiyv** [leon-mbs/zstore#302]
Всі категорії в одній колонці. Це просто але складно шукати товар.

**Comment by leon-mbs** [comment]
ієрархія категорій включається до загальних налаштувань. У вигляді дерева відображається лише в адмінці онлайн каталогу. це не десктопне додаток працювати з деревами у браузері особливо в мобільному телефоні дуже незручно. в інших місцях зазвичай є фільтр за категоріями

**Comment by AlexFromKiyv** [comment]
В Opencart бачив як спробували рішити цю проблему на мобільних але вони не довели до ума. На мобільному можно виводить спочатку основні групи а при вході в гупу висвічувати лише її i підгруппи.  
Можливо це не видно з першого погляду але це дуже вліяє на популярність ПО такого типу. Новий користувач починае з того шо хоче внести свій товар.

**Comment by leon-mbs** [comment]
ця  проблема  зазвичай  у  тих  хто  звик  працювати  з  одноце  або  програмами  з нульвих написаними на  делфI
знову  ж таки програма розрахована  на  малий бiзнес  мало  у кого  настiльки  багато  категорiй
знову  ж тики  це  в  першу  чергу складський  облiк - а  в накладних  все  одно нема  нiяких категорiй, тай  не  треба  бо  для  складу достатньо  артикула
це  покупцям  в  IM   потрiбнI дерева  бо  вони не  знають  що  де  шукати

**Comment by AlexFromKiyv** [comment]
Можливо для цього проекту ви праві. Успіхів.
