### ISSUE TITLE
Дашборд 

### ISSUE THREAD

**Issue by svafn** [leon-mbs/zstore#451]
В "Дашборд" інтуїтивно чекаєш, що можна клацнути на верхні іконки, котрі відкриють сторінки з додатковою інформацією. Але вони не клікабельні.

**Comment by leon-mbs** [comment]
справа  в  тому що  цi цифри   - збiрна  iнфа   а не просто цифра  якоiсь   сторiнки
куди напримлкл  перейти  с дебету - на  сторiнку  розрахункiв з  постачальниками  чи   з  покупцясми?
дебетовий  борг  може  бути  у  тих  i у  тих
 

--
