### ISSUE TITLE
Помилка в звіті товари в дорозі

### ISSUE THREAD

**Issue by klochko** [leon-mbs/zstore#683]
Привіт

Якщо створити заявку постачальнику і клікнуть клавішу на виконання то в звіті товари в дорозі нічого не з'являється. 

Дякую

**Comment by klochko** [comment]
Можливо це через те що документ стає проведеним замість статуса виконується.

**Comment by leon-mbs** [comment]
так  тре  шоб  будо  виконується 
потiм  товар  типу  прийшов  i  заявку  тре перевести в  втконана
